### ISSUE TITLE
Donation 이벤트 문제

### ISSUE THREAD

**Issue by yj0524** [kimcore/chzzk#1]
chzzkChat.on으로 donation 이벤트를 수신할 때, 처음 시작 시에만 작동하고 chat 이벤트처럼 이벤트가 감지될때마다 새로 올라오지 않는 문제가 있습니다. systemMessage도 똑같을 것으로 예상됩니다.

**Comment by kimcore** [comment]
구조가 변경된 듯 하네요 ㅠ`1.0.7` 버전으로 업데이트 하시면 수정됩니다! 제보 감사합니다.

**Comment by yj0524** [comment]
아직 수정되지 않은 것 같아요! 재확인 부탁드립니다

**Comment by kimcore** [comment]
커밋이 꼬여서 코드 변경이 안되었던 듯 합니다! `1.0.9` 버전으로 다시 시도해보시겠어요?

**Comment by yj0524** [comment]
확인하였습니다 감사합니다
