### ISSUE TITLE
disconnect() 메서드에 문제가 있는 것 같습니다.

### ISSUE THREAD

**Issue by b4psa3** [kimcore/chzzk#10]
```js
async disconnect() {
  if (!this.connected) {
    throw new Error('Not connected')
  }
  // 이하 코드 생략
}
```
현 시점 모듈 코드의 채팅``disconnect()`` 메서드 코드 일부입니다. 위 코드 진행대로라면 계정(봇) 이 채팅에 연결되어 있지 않을 때 ***Not connected*** 오류가 발생하며 코드 진행이 중단되게 되는 것 같습니다.
disconnect() 메서드를 사용하지 않는다면 발생하지 않을 문제지만, ``chatChannelId``가 채널별 고정이 아닌 세션별 랜덤 생성이라는 점에서 ``disconnect()`` 메서드의 사용은 불가피할 것으로 판단됩니다.
위 코드를 ***오류가 발생하면 해당 오류를 알려주고 다시 시도*** 와 같이 프로그램이 다운되지 않도록 바꿔주실 수 있을까요?

**Comment by kimcore** [comment]
`disconnect` 메서드의 사용이 불가피하다는 말씀은 잘 이해가 되지 않으나,
`ChzzkChat` 클래스의 `connected` 프로퍼티를 통해서 연결이 되어 있는지 여부를 확인하실 수 있습니다.
해당 프로퍼티를 통해 연결 여부를 확인 후 `disconnect` 메서드를 사용하시면 될 듯 합니다.

**Comment by b4psa3** [comment]
답변 감사합니다. 말씀해 주신 대로 컨디션 체크 후 ``disconnect``메서드를 적절히 사용하는 방향으로 수정해 보겠습니다.
추가로, 앞서 말씀드린 **``chatChannelId``의 랜덤성** 은 테스트 중 다른 이슈가 겹쳐 잘못 판단한 것 같아 현재로썬 이 부분은 무시하셔도 될 것 같습니다.

본 이슈는 ``해결됨`` 상태로 직접 닫겠습니다.
