### ISSUE TITLE
followDate

### ISSUE THREAD

**Issue by atts1775** [kimcore/chzzk#11]
스트리머의 chatChannel 에서 특정 user의 followDate 값을 가져오고 싶은데 api를 추가해주실 수 있나요?
https://comm-api.game.naver.com/nng_main/v1/chats/${chatChannelId}/users/${userIdHash}/profile-card?chatType=STREAMING

**Comment by kimcore** [comment]
`1.3.0` 버전에 추가하였습니다! 제보 감사합니다.

```ts
// 만약 ChzzkChat 내부에서 현재 chatChannelId를 불러오고 싶으시다면
// chzzkChat.chatChannelId 를 사용하시면 됩니다.

client.chat.profileCard(chatChannelId, userIdHash)
```
