### ISSUE TITLE
README.md 수정 요청

### ISSUE THREAD

**Issue by yj0524** [kimcore/chzzk#12]
```js
// 유저의 팔로우 일시 불러오기
// client.chat.profileCard(chzzkChat.chatChannelId, chat.profile.userIdHash).then(profile => {
//     console.log(profile.following ? `${profile.following.followDate} 에 팔로우 함` : "팔로우 안함")
// })
```

위 예시를 보면 `profile.following`과 `profile.following.followDate`가 있습니다.
하지만, 실제 API를 보면 `profile.streamingProperty.following`과 `profile.streamingProperty.following.followDate`로 되어있습니다.
위 텍스트를 수정해주시면 감사하겠습니다.

**Comment by kimcore** [comment]
수정했습니다! 제보 감사합니다 :)
