### ISSUE TITLE
subscription 이벤트 웹소켓

### ISSUE THREAD

**Issue by yj0524** [kimcore/chzzk#19]
msgTypeCode (코드 내 기준 ChatType) 는 11이고, cmd (코드 내 기준 ChatCmd) 는 93102로 확인되었습니다.
아래 스크린샷 확인 부탁드립니다.

![스크린샷 2024-03-08 220722](https://github.com/kimcore/chzzk/assets/78587308/abbf3aff-4593-4b7a-b0ce-007f6d635517)

subscription 이벤트를 추가하는 데 도움이 될 것 같아 올립니다.

**Comment by kimcore** [comment]
`1.6.0` 버전에 추가하였습니다. 제보 감사합니다!
