### ISSUE TITLE
[Bug] 검색 결과가 없을 시 오류 발생

### ISSUE THREAD

**Issue by Helloyunho** [kimcore/chzzk#2]
검색 결과가 없을 때 `content.page`가 null로 대체되는데,
이것이 제대로 처리되지 않아 `content.page.next.offset`을 불러오려 할 때 오류가 발생합니다.

https://github.com/kimcore/chzzk/blob/main/src/api/search.ts#L59
https://github.com/kimcore/chzzk/blob/main/src/api/search.ts#L81
https://github.com/kimcore/chzzk/blob/main/src/api/search.ts#L109

추가로, `search` 메소드의 반환 타입을 제대로 지정하여 추후 이런 문제가 재발하지 않도록 하는것도 좋아보이네요.

**Comment by kimcore** [comment]
`1.0.9` 버전에서 수정되었습니다. 제보 감사합니다!
