### ISSUE TITLE
메시지 고정 / 메시지 블라인드

### ISSUE THREAD

**Issue by hellow0709** [kimcore/chzzk#28]
메시지 고정과 메시지 블라인드 방법좀 알려주세요~~
멤버 차단 부분도여

**Comment by yj0524** [comment]
- 메시지 고정
```js
const message = "TEST MESSAGE";

const options = {
    message,
    messageTime: new Date().getTime(),
    messageUserIdHash: senderId,
    streamingChannelId: channelId,
    extras: {}
};

await client.chat.notice(chatChannelId, options);
```

- 임시 제한
```js
await client.manage.temporaryRestrict(channelId, targetId);
```

- 활동 제한
```js
await client.manage.restrice(channelId, targetId);
```

- 메시지 블라인드 (임시 제한, 활동 제한 시 자동으로 적용됨.) (특정한 메시지 한개만 블라인드처리할 때는 #29 참조. (Pull Request Merge 시 사용 가능))

**Comment by hellow0709** [comment]
디스코드 문의좀 할 수 있게 "5ray__" 디엠좀 받아주세요.
  chzzkChat = czclient.chat({
    channelId: channel.channelId,
    pollInterval: 30 * 1000,
  });

		await czclient.chat.blind(chzzkChat.chatChannelId, options);
		이런식으로 하는게 맞는가요?

**Comment by kimcore** [comment]
`1.9.0` 버전으로 업데이트 하시면 메시지 블라인드 기능을 사용하실 수 있습니다.
```ts
const options = {
    message: chat.message,
    messageTime: chat.time,
    messageUserIdHash: chat.profile.userIdHash,
    streamingChannelId: channelId
}

await client.chat.blind(chatChannelId, options)
```
