### ISSUE TITLE
chzzk manage 이상

### ISSUE THREAD

**Issue by hellow0709** [kimcore/chzzk#31]
예를 들어서
소스코드 중에서
  | return this.client.fetch(`/manage/v1/channels/${channelId}/temporary-restrict-users`, {
  | method: "POST",
  | headers: { "Content-Type": "application/json" },
  | body: JSON.stringify({ targetId })

이 부분에서 temporary-restrict-users로 post를 보낼때 body가 chatchannelid도 포함되어야 하는게 아닌가요?

**Comment by kimcore** [comment]
`1.10.0` 버전에서 수정하였습니다. 제보 감사합니다!
