### ISSUE TITLE
Chat list is not iterable

### ISSUE THREAD

**Issue by yj0524** [kimcore/chzzk#4]
프로그램 실행 중, 간헐적으로 채팅을 받아올 때 #3 와 똑같은 오류가 발생합니다.

환경 : ```Node.js 18, 19, 20, 21``` | ```Bun 1.0.15, 1.0.16, 1.0.17, 1.0.18, 1.0.19, 1.0.20```

**Comment by kimcore** [comment]
시스템 메시지에 관련된 이슈인 듯 합니다. 현시점에서는 자유롭게 관련 테스트를 하는 것이 불가능하므로, 정식 출시 이후 관련 테스트가 가능해지면 수정하도록 하겠습니다. 
그 전까지는 우선 `1.0.11` 버전을 사용하시면서 `Chat list is not iterable`이라는 오류가 발생할 경우 이 이슈 페이지에 제보해주시면 감사하겠습니다.

**Comment by yj0524** [comment]
![스크린샷 2024-01-02 174920](https://github.com/kimcore/chzzk/assets/78587308/2159b78c-833a-4df8-bab1-4913fbbf22e7)
2시간정도 돌려본 결과
위 사진처럼 Chat list is not iterable. (94008) 메시지가 9번 발생하였습니다.

**Comment by kimcore** [comment]
채팅/도네이션 외의 기타 이벤트를 같은 방식으로 처리하려 하니 발생한 문제였던 듯 합니다!
`1.1.0` 버전에서 해결되었습니다.
