### ISSUE TITLE
채널의 방송이 종료되었을 때 프로그램 실행이 중단됨

### ISSUE THREAD

**Issue by yj0524** [kimcore/chzzk#5]
client.search.channels("asdf") 코드를 넣었다고 했을 때,
asdf의 방송이 꺼지면 프로그램 실행이 중단되는 문제가 있습니다.

**Comment by kimcore** [comment]
해당 코드만으로 프로그램 실행이 중단된다는 것은 이해하기 어렵네요 ㅠ
사용하신 코드의 일부분을 보내주셔야 도움을 드릴 수 있을 듯 합니다.

**Comment by yj0524** [comment]
치지직 챗봇을 만드려고 여러 채널에서 작동하게 수정한 제 코드가 잘못되었던 것 같습니다.
항상 이슈 확인해주시고 수정해주셔서 감사합니다.
이슈는 Close as not planned 상태로 닫겠습니다.
