### ISSUE TITLE
API 버전 자동 변경 

### ISSUE THREAD

**Issue by yj0524** [kimcore/chzzk#7]
현재 v1 API에 들어가면, code 9004와 함께 "앱 업데이트 후에 정상 시청 가능합니다." 메시지가 나옵니다.

코드가 9004라면 v1에서 v2로, v2에서도 코드가 9004라면 v2에서 v3로 자동으로 올려주는 기능이 추가되면 모듈을 계속 업데이트하지 않아도 사용할 수 있을 것 같아 편리할 것 같습니다.

**Comment by kimcore** [comment]
API 버전이 v2로 업데이트될 때는 내부 데이터 구조 변경이 크게 없었으나 보통 API 버전이 업데이트될 경우 내부 데이터의 구조나 요청 방식 등이 변경되기 때문에 결국은 모듈 업데이트가 필요하게 될 것이라고 생각됩니다. 좋은 제안은 감사드립니다!
