### ISSUE TITLE
방송이 시작된 후 채팅 받아오기 멈춤

### ISSUE THREAD

**Issue by yj0524** [kimcore/chzzk#9]
방송이 켜져있을 때 친 채팅은 제대로 나오지만,
방송이 꺼진 후의 채팅은 나오지 않는 것으로 보입니다.
이로 인해 방송이 켜질 때마다 코드를 재실행해줘야하는 문제가 있습니다.
이 문제를 수정하면 채팅창에서 치지직 채팅창이 방송을 시작했을 때 새로고침을 하지 않아도 제대로 채팅이 나올 것 같습니다.

**Comment by yj0524** [comment]
업데이트합니다. 방송이 꺼진 후 채팅은 제대로 받아와집니다. 방송이 꺼진 후 다시 켜졌을 때에만 해당되는 것으로 보입니다.

**Comment by yj0524** [comment]
방송이 시작될 때마다 chatChannelId가 변경되는 문제로 인해 발생한 오류로 보입니다.

**Comment by kimcore** [comment]
답변이 늦어 죄송합니다! 

공식 사이트를 모방하여 일정 주기마다 `chatChannelId` 의 변경을 체크할 수 있도록 `1.2.0` 버전에 `pollInterval` 옵션을 추가하였습니다.
`chatChannelId` 가 변경된 것이 확인될 경우 자동으로 새로운 `chatChannelId` 로 재연결하게 됩니다.

ChzzkChat 인스턴스를 생성할 때 `channelId` 값을 넘겨주도록 변경되었으니 아래 코드를 참고 부탁드립니다.
`channelId` 값만 넘겨주면 `chatChannelId`, `accessToken` 값은 내부에서 자동으로 불러오게 되어있습니다.
```ts
const client = new ChzzkClient()

const result = await client.search.channels("녹두로로")
const channel = result.channels[0]
    
const chzzkChat = client.chat({
    channelId: channel.channelId,
    pollInterval: 30 * 1000 // channelId를 지정할 경우 자동으로 30초로 설정됨
})
```
